--- #YAML:1.0
name:               Mac-SleepEvent
version:            0.02
abstract:           run Perl code on Mac OS X sleep and wake events
author:
    - Lee Aylward <leedo@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Foundation:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
